### ISSUE TITLE
Oficina Virtual de la Consejería de Hacienda y Financiación Europea, Junta de Andalucía

### ISSUE THREAD

**Issue by antjavbec** [PucelaBits/websegura#102]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Provincia/Comunidad: Sevilla/Comunidad Autónoma de Andalucía

```
{
    "url": "https://www.juntadeandalucia.es/haciendayadministracionpublica/ov/",
    "name": "Oficina Virtual de la Consejería de Hacienda y Financiación Europea de la Junta de Andalucía",
    "twitter": "usuarioTwitter1"
}
```

**Comment by nukeador** [comment]
Hola,

La web y dominio www.juntadeandalucia.es lo analizamos ya en la página de Andalucía, por lo que todas sus subpáginas tienen la misma nota:

https://websegura.pucelabits.org/c/andalucia/

Muchas gracias y no dudes en enviarnos cualquier otra web que falte :-)
