### ISSUE TITLE
Ayuntamiento de Algeciras

### ISSUE THREAD

**Issue by dragoncleo** [PucelaBits/websegura#109]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Provincia/Comunidad: Cádiz/Andalucía

```
{
    "url": "www.algeciras.es",
    "name": "Ayuntamiento de Algeciras",
    "twitter": "aytoalgeciras"
},

```

**Comment by nukeador** [comment]
Muchas gracias por el aporte. Ya lo hemos subido y estará en unos minutos en la web.
