### ISSUE TITLE
Enlace a twitter activado en algunas webs seguras

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#112]
**Describe el problema**
Sitios verdes tienen el enlace de twitter activado y no debería

**Para reproducirlo**
Para para reproducir el problema:
1. Ir a la home
2. Haz scroll hasta abajo para llegar a las mejores webs (verdes)
3. Ver que sale enlace de twitter

**Capturas de pantalla**
![Screenshot 2021-02-11 at 14 51 20](https://user-images.githubusercontent.com/673420/107696439-3ee36300-6cb2-11eb-96db-acfc8592182e.png)

**Comment by fcoterroba** [comment]
Podéis asignármelo si queréis, creo que puedo hacerlo!

**Comment by palmerabollo** [comment]
Me comenta @nukeador que es lo esperado, sale hasta nivel B-.
Gracias por el ofrecimiento, en cuanto vea alguna buena para iniciarse, te menciono @fcoterroba
