### ISSUE TITLE
Datos de ubicación - Soporte para más provincias

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#12]
Quizá sería buena idea añadir un campo de "municipio" o similar para que si a futuro se añaden webs de otras ciudades de CyL (o por qué no, del resto de España), podamos filtrar por país.

¿Qué vamos a hacer con webs que son provinciales o regionales?

**Comment by palmerabollo** [comment]
Quizá el enrutado de 11ty permita tener URLs bonitas del estilo https://websegura.pucelabits.org/$municipio y cargar la página con los datos filtrados.

Puede que haya organismos donde no haya un mapeo geográfico a una ciudad (ej. Junta de Castilla y León o Vinos de Ribera del Duero).

**Comment by adrm** [comment]
Si, podríamos hacer eso sin problema, pero entonces la raíz mostraría una tabla con todo? Varias tablas con las webs de cada zona? Un resumen de cada zona y enlace a ver una tabla con las páginas de esa zona?

Yo lo que imaginaba es dejar la estructura prácticamente como ahora, y facilitar que otras organizaciones pudieran reutilizar nuestro código. Depende de hasta dónde queramos/podamos abarcar.

**Comment by nukeador** [comment]
Siento que es más fácil para personas interesadas en el tema añadir webs y municipios a nuestro archivo, que clonar y mantener un fork y web. Pueden hacerlo si quieren, pero creo que si optimizamos ahora para que pueda suceder todo aqui si hay gente que quiere, va a ser positivo al largo plazo.

Además que ayuda a dar más visibilidad a pucelabits que solo el ámbito local.

**Comment by adrm** [comment]
Estoy de acuerdo, se aprovecharía mejor el trabajo hecho si permitimos ampliarlo de esa forma. Dicho esto, habría que pensar cómo resumir la información en el index.

**Comment by nukeador** [comment]
Quizá que la palabra Valladolid del título estuviera algo así con un triagulito para poder hacer clic y desplegar, seleccionando otras provincias/municipios

![imagen](https://user-images.githubusercontent.com/531906/104943385-f89e2b00-59b5-11eb-9d96-2556841f8fc2.png)

**Comment by palmerabollo** [comment]
Se me ha ocurrido una idea que me parece bastante flexible. Sería dar "tags" a los sitios. Por ejemplo "valladolid", "castilla-y-leon", "denominaciones-de-origen", "partidos-politicos"... lo que queramos. De esta forma:
1. Un sitio puede pertenecer a N clasificaciones (p.e. la página del PSOE de Valladolid podría ser "valladolid", "partidos-politicos")
2. Admitiríamos cualquier url https://websegura.pucelabits.org/$tag, que filtraría directamente lo que tenga ese tag.

La única duda es qué hacer si no pones ningún tag.

**Comment by nukeador** [comment]
De usar tags, deberíamos definir una lista consistente. Y tener una forma de mostrar una lista de tags que son ubicaciones, otro grupo que son partidos... no se si eso hace mucho más complejo todo con subniveles.

Porque por defecto queremos una vista de organismos públicos en Valladolid para hacer ruido en redes inicialmente ¿no?

**Comment by adrm** [comment]
Yo separaría entre localizaciones y tipos, no solo tags de forma genérica. Así, podríamos tener páginas tipo `/lugar/valladolid` que mostraran una tabla con todas las páginas de un sitio, mostrando su tipo, y '/tipo/partido-politico` que haría lo contrario. Aún así me quedaría la duda de qué mostrar en la página principal. En un primer momento podríamos mostrar una tabla por cada lugar directamente en el index, y ya pensaremos qué priorizar o cómo organizarlo cuando tengamos demasiadas páginas. ¿Os parece tirar de esta forma?

**Comment by nukeador** [comment]
A mi me suena bien, lo que menos dolores de cabeza de a posteriori. Yo creo que en general la gente va a querar mirar de primeras por lugar.

**Comment by nukeador** [comment]
Actualmente los problemas a solucionar son:

- Queremos que el archivo para añadir URLs no sea gigante, y que sea fácil de mantener por un grupo. Lo ideal es que sea por provincia.
- Queremos incluir URLs de organismos sólo regionales, de cada comunidad autónoma.
- Puede que a futuro queramos meter organismos sólo de nivel nacional.
- Queremos poder mostrar estos datos en la web con el nivel de zoom que el usuario prefiera (Ver sólo de Valladolid, sólo regionales, todos los de CyL y provincias...)

**Comment by nukeador** [comment]
Una de las opciones propuestas es:

- Tener un archivo por provincia
- Tener un archivo por comunidad sólo con las URLs de nivel regional.
- Añadir metadatos a todas las URLs para saber si son locales o regionales.

**Comment by adrm** [comment]
Primera prueba de implementación de esto en https://github.com/PucelaBits/websegura/pull/28

**Comment by nukeador** [comment]
Está genial, he pedido a conocidos de otras provincias si nos pueden pasar webs locales para tener al menos una más y ver cómo lo mostramos.

**Comment by nukeador** [comment]
Ya tenemos una primera aproximación, seguimos en issues individuales.
