### ISSUE TITLE
Soporte para etiquetas

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#121]
Venimos de #113

Abro para hacer tracking del progreso aquí.

**Comment by nukeador** [comment]
@palmerabollo hice un fix para que cargue al poner /l/algo/ con la barra final para que genere el html.

Puse /l/ para mantener la consistencia con el resto de la web.

**Comment by nukeador** [comment]
Aquí podríamos añadir slug para diferenciarlo del name

https://github.com/PucelaBits/websegura/blob/a16949574d42bb1bb7defa8aba0bcb6c945cfc63/_data/tags.json#L3

De esta forma podemos listar todas las etiquetas con su nombre y que no sean sus slugs en minúscula.

**Comment by palmerabollo** [comment]
Ok, del /l/ /p/ /c/ ya hablaremos :D Creo que para el SEO es mejor poner una palabra, para que si alguien busca "lista de ministerios" salga más arriba en Google. Pero tampoco soy experto.

**Comment by nukeador** [comment]
@palmerabollo ¿Podemos decir que la implementación ya está terminada y podemos cerrar? ¿Abrimos otras issues para otros detalles?

**Comment by adrm** [comment]
Justo venía a preguntar si dábamos esto por cerrado. Creo que la funcionalidad básica está y ayudaría hacer issues concretos con las funcionalidades que se consideren a mayores.
