### ISSUE TITLE
coruna.es

### ISSUE THREAD

**Issue by e-admon** [PucelaBits/websegura#124]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Provincia/Comunidad: MiProvincia/MiComunidad

```
{
    "url": "www.web1.com",
    "name": "El Nombre 1",
    "twitter": "usuarioTwitter1"
},
{
    "url": "www.web2.com",
    "name": "El Nombre2",
    "twitter": "usuarioTwitter"2
}
```

**Comment by nukeador** [comment]
Hola,

Parece que no has modificado la plantilla para añadir la dirección, el nombre y el twitter. ¿Podrías revisarlo?

Gracias.

**Comment by e-admon** [comment]
Hola,
La verdad es que es la primera vez que entro en esta comunidad. No tengo
conocimientos de programación ni lenguajes computacionales.
En realidad sólo quería añadir esa web al listado de sitios públicos
analizados.
No pretendía más que ese propósito.
Disculpad si no supe hacerlo correctamente.
Un saludo y gracias por tu atención.

**Comment by nukeador** [comment]
No te preocupes. Entiendo que quieres añadir coruna.es ¿no? Por lo que veo redirige a www.coruna.gal

Necesitaríamos saber el twitter oficial de cada sitio web y qué nombre poner. Aquí entiendo que es

{
    "url": "www.coruna.gal",
    "name": "Ayuntamiento de A Coruña",
    "twitter": "ConcelloCoruna"
}

¿Es correcto? Si tienes otras webs de A Coruña las podemos añadir todas juntas.

**Comment by e-admon** [comment]
Exactamente.
{
"url": "www.coruna.gal",
"name": "Ayuntamiento de A Coruña",
"twitter": "@ConcelloCoruna"
}
Gracias por tu ayuda.
Tienen registrados varios dominios, pero por normalización lingüística
redirige al .gal

Otras 2 webs de AAPP que me gustaría que, de ser posible, fueran analizadas
serían:

- La Diputación de Coruña:
{
"url": "www.dacoruna.gal",
"name": "Diputación de A Coruña",
"twitter": "@DACturismo"
}


Y la autonómica con sus *desbordantes* medios, Xunta de Galicia:

{
"url": "www.xunta.es",
"name": "Xunta de Galicia",
"twitter": "@xunta"
}

Gracias por vuestro trabajo y tu amabilidad.

Saludos.

**Comment by adrm** [comment]
Muchas gracias por tu colaboración, acabo de añadir las páginas que nos has solicitado. La de la Xunta ya estaba añadida. Puede que tarde unas horas hasta que se realice el análisis inicial y aparezcan los resultados en la página.

¡Un saludo!

**Comment by e-admon** [comment]
Muchas gracias Adrián.
Creo que estáis haciendo un gran trabajo.
Los más interesados somos los ciudadanos.
Por cierto, si más adelante disponéis de más medios y colaboraciones
podríais intentar testear la seguridad de la sedes electrónicas de las
Administraciones Públicas, porque las webs tienen importancia, pero lo
realmente delicado y con implicaciones jurídicas efectivas son las sedes.
Saludos.

**Comment by adrm** [comment]
Si conoces las páginas de esas sedes electrónicas y nos lo pasas en el formato que te indicábamos, podremos añadirlas rápidamente. Desgraciadamente, es imposible afirmar que algo sea totalmente seguro, el análisis que hacemos solo cubre una serie de ataques que consideramos importantes porque son técnicamente fáciles de ejecutar y a la vez fáciles de prevenir.

Así que esperamos futuros issues si tienes más webs públicas que quieras añadir!

Gracias,

**Comment by e-admon** [comment]
Hola de nuevo

Disculpad la chapa...

Me refería a esto:

{
"url": "sede.coruna.gob.es",
"name": "Ayuntamiento de A Coruña",
"twitter": "ConcelloCoruna"
}

No sé si es posible. En todo caso la diferencia es que mientras la web es
un simple portal de información en internet, lo "importante" está o se
gestiona a través de su sede.

Si hay alguna duda, mirad las diferencias entre el artículo 39 y el 38 de
la ley que regula toooodo el cotarro administrativo público en España:
https://www.boe.es/eli/es/l/2015/10/01/40/con

Saludos y gracias de nuevo por la atención y la gestión.

**Comment by adrm** [comment]
Añadida la sede electrónica. Gracias!
