### ISSUE TITLE
Murcia desaparecida en el ranking provinciañ

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#138]
https://websegura.pucelabits.org/ranking/#ranking-provincial

Por algún motivo no sale Murcia, ¿no falta alguna más?

**Comment by adrm** [comment]
Veo que el script que hace asume que toda provincia está incluída en alguna comunidad, que visto así no es mala asunción, la verdad. Creo que el fix sería crear json de las comunidades que faltan.

**Comment by adrm** [comment]
Murcia HA VUELTO.

Si falta alguna más es cuestión de crear el archivo de comunidad. Ahora no puedo dar el repaso completo.
