### ISSUE TITLE
Enlace para añadir nueva web

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#14]
Sería útil tener un enlace cerca de la tabla que diga algo como:

"¿Conoces alguna otra web de organismos públicos en $LUGAR? <link>Ayúdanos a añadirla</link>"

Y enlazar una sección del readme que explique para gente no técnica como crear un issue y qué datos nos tiene que proporcionar, o para la gente técnica el archivo que tiene que modificar y hacer PR.

**Comment by palmerabollo** [comment]
En github hay "issue templates" para tener una issue con los campos necesarios y cosas así https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository. Podría ser una mejora futura, con lo que hay ahora está bastante claro ya.

**Comment by nukeador** [comment]
Sí, de hecho creé 3 templates para los issues, y el enlace en el readme manda al de nuevo sitio 😄
