### ISSUE TITLE
[Puertos del Estado]

### ISSUE THREAD

**Issue by carlicm** [PucelaBits/websegura#158]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Provincia/Comunidad: Madrid/Madrid

```
{
    "url": "www.puertos.es",
    "name": "Puertos del Estado",
    "twitter": "@PuertosEstado",
    "tags": ["Puertos"]
},

**Comment by palmerabollo** [comment]
Añadida, gracias!
