### ISSUE TITLE
Webs del Principado de Asturias

### ISSUE THREAD

**Issue by XtoreX** [PucelaBits/websegura#168]
Asturias: Principado de Asturias

{
    "url": "www.asturias.es",
    "name": "Gobierno del Principado de Asturias",
    "twitter": "@GobAsturias",
},
{
    "url": "www.oviedo.es",
    "name": "Ayuntamiento de Oviedo",
    "twitter": "@aytoviedo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.gijon.es/es",
    "name": "Ayuntamiento de Gijón",
    "twitter": "@gijon",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aviles.es",
    "name": "Ayuntamiento de Avilés",
    "twitter": "@AytoAviles",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.facc.info",
    "name": "Federación Asturiana de Concejos",
    "twitter": "@RedConsolida",
    "tags": ["fundaciones"]
},
{
    "url": "www.allande.es",
    "name": "Ayuntamiento de Allande",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aller.es",
    "name": "Ayuntamiento de Aller",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.amieva.es",
    "name": "Ayuntamiento de Amieva",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.belmontedemiranda.es",
    "name": "Ayuntamiento de Belmonte de Miranda",
    "twitter": "@AytoBelmonte",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.bimenes.es",
    "name": "Ayuntamiento de Bimenes",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.boal.es",
    "name": "Ayuntamiento de Boal",
    "twitter": "@AytoBoal",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.cabrales.es",
    "name": "Ayuntamiento de Cabrales",
    "twitter": "@CabralesAyto",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.cabranes.es",
    "name": "Ayuntamiento de Cabranes",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-castrillon.es",
    "name": "Ayuntamiento de Castrillón",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-caso.es",
    "name": "Ayuntamiento de Caso",
    "twitter": "@CasoRedes",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-carreno.es",
    "name": "Ayuntamiento de Carreño",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytocaravia.com",
    "name": "Ayuntamiento de Caravia",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-cnarcea.es",
    "name": "Ayuntamiento de Cangas del Narcea",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.candamo.es",
    "name": "Ayuntamiento de Candamo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.cangasdeonis.es",
    "name": "Ayuntamiento de Cangas de Onís",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.onis.es",
    "name": "Ayuntamiento de Onís",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytonorena.es",
    "name": "Ayuntamiento de Noreña",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-navia.es",
    "name": "Ayuntamiento de Navia",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-nava.es",
    "name": "Ayuntamiento de Nava",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.murosdenalon.es",
    "name": "Ayuntamiento de Muros de Nalón",
    "twitter": "@cdtlmuros",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.morcin.es",
    "name": "Ayuntamiento de Morcín",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-mieres.es",
    "name": "Ayuntamiento de Mieres del Camino",
    "twitter": "@AytoMieres",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-laviana.es",
    "name": "Ayuntamiento de Laviana",
    "twitter": "@LavianaGobierno",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytolena.es",
    "name": "Ayuntamiento de Lena",
    "twitter": "@Aytolena",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.llanera.es",
    "name": "Ayuntamiento de Llanera",
    "twitter": "@aytollanera",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayuntamientodellanes.com",
    "name": "Ayuntamiento de Llanes",
    "twitter": "@RedSocialLlanes",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.lasregueras.es",
    "name": "Ayuntamiento de Las Regueras",
    "twitter": "@Las_Regueras",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.langreo.as",
    "name": "Ayuntamiento de Langreo",
    "twitter": "@Ayto_Langreo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-illas.es",
    "name": "Ayuntamiento de Illas",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.illano.es",
    "name": "Ayuntamiento de Illano",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ibias.es",
    "name": "Ayuntamiento de Ibias",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.grandasdesalime.es",
    "name": "Ayuntamiento de Grandas de Salime",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-grado.es",
    "name": "Ayuntamiento de Grado",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-gozon.org",
    "name": "Ayuntamiento de Gozón",
    "twitter": "@TurismoGozon",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.elfranco.net",
    "name": "Ayuntamiento de El Franco",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.degania.org",
    "name": "Ayuntamiento de Degaña",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.cudillero.es",
    "name": "Ayuntamiento de Cudillero",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.corvera.es",
    "name": "Ayuntamiento de Corvera",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.colunga.es",
    "name": "Ayuntamiento de Colunga",
    "twitter": "@cultura_colunga",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayuntamientodecoana.com",
    "name": "Ayuntamiento de Coaña",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.castropol.es",
    "name": "Ayuntamiento de Castropol",
    "twitter": "@AytoCastropol",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.villayon.es",
    "name": "Ayuntamiento de Villayón",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.yernesytameza.es",
    "name": "Ayuntamiento de Yernes y Tameza",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.valdes.es",
    "name": "Ayuntamiento de Valdés",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.villaviciosa.es",
    "name": "Ayuntamiento de Villaviciosa",
    "twitter": "@AytoVillaAst",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.tapiadecasariego.es",
    "name": "Ayuntamiento de Tapia de Casariego",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.santirsodeabres.es",
    "name": "Ayuntamiento de San Tirso de Abres",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.sotodelbarco.com",
    "name": "Ayuntamiento de Soto del Barco",
    "twitter": "@oficinasotobarc",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.tineo.es",
    "name": "Ayuntamiento de Tineo",
    "twitter": "@TurismoTineo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytoteverga.org",
    "name": "Ayuntamiento de Teverga",
    "twitter": "@Tevergaturismo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-sobrescobio.es",
    "name": "Ayuntamiento de Sobrescobio",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-salas.es",
    "name": "Ayuntamiento de Salas",
    "twitter": "@AytoSalas",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.sanmartindeoscos.es",
    "name": "Ayuntamiento de San Martín de Oscos",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.santoadriano.org",
    "name": "Ayuntamiento de Santo Adriano",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.santaeulaliadeoscos.es",
    "name": "Ayuntamiento de Santa Eulalia de Oscos",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ribadedeva.es",
    "name": "Ayuntamiento de Rivadedeva",
    "twitter": "@ribadedeva20",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-ribadesella.es",
    "name": "Ayuntamiento de Ribadesella",
    "twitter": "@AytoRibadesella",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-riberadearriba.es",
    "name": "Ayuntamiento de Ribera de Arriba",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-pravia.es",
    "name": "Ayuntamiento de Pravia",
    "twitter": "@ayto_pravia",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytopbpanes.es",
    "name": "Ayuntamiento de Peñamellera Baja",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.aytopenamelleraalta.es",
    "name": "Ayuntamiento de Peñamellera Alta",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ponga.es",
    "name": "Ayuntamiento de Ponga",
    "twitter": "@bibliotecadepon",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.proaza.es",
    "name": "Ayuntamiento de Proaza",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayuntamientoriosa.com",
    "name": "Ayuntamiento de Riosa",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.smra.org",
    "name": "Ayuntamiento de San Martín del Rey Aurelio",
    "twitter": "@SanMartin_ayto",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.sariego.org",
    "name": "Ayuntamiento de Sariego",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.taramundi.es",
    "name": "Ayuntamiento de Taramundi",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-pilona.es",
    "name": "Ayuntamiento de Piloña",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.somiedo.es",
    "name": "Ayuntamiento de Somiedo",
    "twitter": "@Cdtlsomiedo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.pesoz.es",
    "name": "Ayuntamiento de Pesoz",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.quiros.es",
    "name": "Ayuntamiento de Quirós",
    "twitter": "@ValleDeQuiros",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.vegadeo.es",
    "name": "Ayuntamiento de Vegadeo",
    "twitter": "@AytodeVegadeo",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.villanuevadeoscos.es",
    "name": "Ayuntamiento de Villanueva de Oscos",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-siero.es",
    "name": "Ayuntamiento de Siero",
    "twitter": "@AytoSiero",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.ayto-parres.es",
    "name": "Ayuntamiento de Parres",
    "twitter": "@PARRESCDTL",
    "tags": ["ayuntamiento"]
},
{
    "url": "www.turismocangasdeonis.com",
    "name": "Turismo de Cangas de Onís",
    "twitter": "@cangasdeonis_",
    "tags": ["ayuntamiento", "fundaciones"]
},

**Comment by palmerabollo** [comment]
Añadidas. Gracias 🎉
