### ISSUE TITLE
Diseño "responsivo"

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#17]
Se puede mejorar la página para que la tabla cargue bien en un móvil, sin necesidad de hacer scroll

**Comment by nukeador** [comment]
No se si a la segunda columna se le puede poner un max-width y que se baje de linea si el dominio es superlargo, como pasa con el centro miguel delibes.

**Comment by nukeador** [comment]
Creo que con los cambios que metí, la tabla ya no hace scroll en móvil.

Si hay otros cambios para ser más responsive, abramos otro issue.
