### ISSUE TITLE
[Nuevo sitio]

### ISSUE THREAD

**Issue by ihsanshade** [PucelaBits/websegura#177]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Provincia/Comunidad: MiProvincia/MiComunidad

```
{
    "url": "http://www.alegria-dulantzi.eus",
    "name": "Alegria-Dulantzi",
    "twitter": "sin twitter",
    "tags": ["ayuntamientos"]
},
{
    "url": "www.web2.com",
    "name": "El Nombre2",
    "twitter": "usuarioTwitter",
    "tags": ["fundaciones"]
},
{
    "url": "www.web3.com",
    "name": "El Nombre3",
    "twitter": "usuarioTwitter"
}
```

**Comment by palmerabollo** [comment]
Incluida en Álava, gracias. Si puedes, para nuevos sitios dinos en qué provincia está y así la damos de alta más rápido. Gracias por contribuir.
