### ISSUE TITLE
[Nuevo sitio]Lobón (Badajoz)

### ISSUE THREAD

**Issue by ihsanshade** [PucelaBits/websegura#178]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Provincia/Comunidad: MiProvincia/MiComunidad

```
{
    "url": "http://www.lobon.es",
    "name": "Lobón",
    "twitter": "sin twitter",
    "tags": ["ayuntamientos"]
},
{
    "url": "www.web2.com",
    "name": "El Nombre2",
    "twitter": "usuarioTwitter",
    "tags": ["fundaciones"]
},
{
    "url": "www.web3.com",
    "name": "El Nombre3",
    "twitter": "usuarioTwitter"
}
```

**Comment by palmerabollo** [comment]
@ihsanshade primera contribución de Extremadura. Gracias! He aprovechado para meter los ayuntamientos de Cáceres y Badajoz. En unos minutos estará en la web.
