### ISSUE TITLE
Asturias: Principales Museos y Puertos

### ISSUE THREAD

**Issue by XtoreX** [PucelaBits/websegura#179]
Asturias: Principado de Asturias

{
    "url": "www.puertogijon.es",
    "name": "Autoridad Portuaria de Gijón",
    "twitter": "PuertodeGijon",
    "tags": ["entidad-publica"]
},
{
    "url": "www.puertoaviles.es",
    "name": "Autoridad Portuaria de Avilés",
    "tags": ["entidad-publica"]
},
{
    "url": "www.turismoasturias.es",
    "name": "Turismo de Asturias",
    "twitter": "TurismoAsturias",
    "tags": ["entidad-publica"]
},
{
    "url": "trabajastur.asturias.es",
    "name": "trabajAstur - Portal del Servicio de Empleo",
    "twitter": "GobAsturias",
    "tags": ["entidad-publica"]
},
{
    "url": "www.museobbaa.com",
    "name": "Museo de Bellas Artes de Asturias",
    "twitter": "MBellasArtesAs",
    "tags": ["museo"]
},
{
    "url": "www.museojurasicoasturias.com",
    "name": "Museo del Jurásico de Asturias",
    "twitter": "Museojurasico",
    "tags": ["museo"]
},
{
    "url": "www.museodelasidra.com",
    "name": "Museo de la Sidra de Asturias",
    "twitter": "MuseodelaSidra",
    "tags": ["museo"]
},
{
    "url": "museoarqueologicodeasturias.com",
    "name": "Museo Arqueológico de Asturias",
    "tags": ["museo"]
},
{
    "url": "www.mumi.es",
    "name": "Museo de la Minería y de la Industria de Asturias",
    "tags": ["museo"]
},
{
    "url": "www.museodeloro.es",
    "name": "Museo del Oro de Asturias",
    "twitter": "MOroAsturias",
    "tags": ["museo"]
},
{
    "url": "www.parquedelaprehistoria.es",
    "name": "Parque de la Prehistoria de Teverga",
    "twitter": "ParqPrehistoria",
    "tags": ["museo"]
},
{
    "url": "www.evaristovalle.com",
    "name": "Fundación Museo Evaristo Valle",
    "twitter": "evaristo_valle",
    "tags": ["museo", "fundaciones"]
},
{
    "url": "www.museominadearnao.es",
    "name": "Museo de la Mina de Arnáu",
    "twitter": "museominaarnao",
    "tags": ["museo"]
},
{
    "url": "www.ecomuseominero.es",
    "name": "Ecomuseo Minero Valle de Samuño",
    "twitter": "ecomuseominero",
    "tags": ["museo"]
},
{
    "url": "www.museodelaescuelarural.com",
    "name": "Museo de la Escuela Rural",
    "twitter": "MERACabranes",
    "tags": ["museo"]
},
{
    "url": "www.museoanton.com",
    "name": "Centro de Escultura de Candás Museo Antón",
    "twitter": "MuseoAnton",
    "tags": ["museo"]
},
{
    "url": "www.mazonovo.es",
    "name": "Museo de los Molinos de Mazonovo",
    "tags": ["museo"]
},
{
    "url": "www.catedraldeoviedo.com",
    "name": "Museo de la Iglesia de Oviedo",
    "twitter": "Catedral_Oviedo",
    "tags": ["museo"]
},
{
    "url": "www.centrotitobustillo.com",
    "name": "Centro de Arte Rupestre de Tito Bustillo",
    "twitter": "CARTitoBustillo",
    "tags": ["museo"]
},
{
    "url": "www.archivodeindianos.es",
    "name": "Fundación Archivo de Indianos - Museo de la Emigración",
    "tags": ["museo", "fundaciones"]
},
{
    "url": "www.centroniemeyer.es",
    "name": "Centro Niemeyer",
    "twitter": "CentroNiemeyer",
    "tags": ["museo"]
},
{
    "url": "www.prerromanicoasturiano.es",
    "name": "Centro de Recepción e Interpretación del Prerrománico Asturiano",
    "twitter": "prerromanico",
    "tags": ["museo"]
},
{
    "url": "www.museobarjola.es",
    "name": "Museo Juan Barjola",
    "tags": ["museo"]
},
{
    "url": "www.museoycircuitofernandoalonso.com",
    "name": "Museo y Circuito Fernando Alonso",
    "twitter": "CircuitoMuseoFA",
    "tags": ["museo"]
},
{
    "url": "www.territoriomuseo.com",
    "name": "Centro de Interpretación de Bustiello",
    "tags": ["museo"]
},
{
    "url": "www.laboralcentrodearte.org",
    "name": "LABoral Centro de Arte y Creación Industrial",
    "twitter": "LABoral",
    "tags": ["museo"]
},
{
    "url": "www.parquenaturalsomiedo.com",
    "name": "Parque Natural de Somiedo",
    "twitter": "pnsomiedo",
    "tags": ["museo"]
},
{
    "url": "www.castrosdeasturias.es",
    "name": "Castros de Asturias",
    "tags": ["museo"]
},
{
    "url": "www.castrillonturismo.es",
    "name": "Turismo de Castrillón",
    "tags": ["fundaciones"]
},
{
    "url": "www.museovinocangas.com",
    "name": "Museo del Vino de Cangas del Narcea",
    "tags": ["museo"]
},
{
    "url": "www.etnoriente.com",
    "name": "Museo Etnográfico del Oriente de Asturias",
    "twitter": "museo_llacin",
    "tags": ["museo"]
},
{
    "url": "www.museodegrandas.es",
    "name": "Museo Etnografico de Grandas de Salime",
    "twitter": "MuseoGrandas",
    "tags": ["museo"]
}

**Comment by palmerabollo** [comment]
Añadidos. Gracias !
