### ISSUE TITLE
El emoji de fuego cae a otra línea

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#191]
**Describe el problema**
Los emojis incluidos recientemente para marcar los sitios "calientes" (con menciones en twitter) no se muestran del todo bien. 

**Para reproducirlo**
Para para reproducir el problema:

1. Entrar a la página principal de la web en el móvil
2. Ver el listado de sitios, los emojis se parten en 2 líneas

**Capturas de pantalla**

![photo_2021-03-08 07 54 50](https://user-images.githubusercontent.com/673420/110285476-98a22900-7fe3-11eb-84d3-b32c08eccc9c.jpeg)

**Comment by XtoreX** [comment]
Si en vez de añadir un emoji de fuego, se cambia el color del pájaro de twitter, se podría conseguir algo similar (gris, amarillo, naranja, rojo,... ) pues se resaltarían los que ya han sido twitteados.

**Comment by nukeador** [comment]
El diseño cambió, ya no tenemos fuegos
