### ISSUE TITLE
Descripción de los sitios

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#2]
Sería bueno describir en una línea qué es cada sitio y quién es el responsable público de ella.

**Comment by adrm** [comment]
Acabo de subir un cambio que hace fácil usar desde la plantilla los datos del CSV, así que podríamos añadir una nueva columna en el CSV con esta información. Si queremos seguir añadiendo metadatos de cada web estaría bien hacer una carpeta con un json por cada web que tenga todos los metadatos necesarios, de forma que pueda seguir funcionando como lo hace ahora pero también permita a eleventy generar una subpágina por cada web que vigilamos, con toda la información extra que queramos.

Lo digo pensando en no llenar demasiado la tabla principal, pero de acuerdo con añadir esa pequeña descripción al menos.

**Comment by nukeador** [comment]
@adrm ¿ahora mismo se lee si hay "description" en el json?

**Comment by adrm** [comment]
> @adrm ¿ahora mismo se lee si hay "description" en el json?

Ahora mismo creo que no pero no habría problema en añadirlo ahora y luego sacarlo del JSON más adelante.

**Comment by palmerabollo** [comment]
Ya se copia el fichero sites.json tal cual, con todos los campos. Si incuimos un campo description en el JSON, automáticamente pasa a estar disponible para pintarlo en el index.html como cualquier otro campo.

**Comment by palmerabollo** [comment]
Creo que el "name" que tenemos es ya muy parecido (o lo mismo) que esa descpición (p.e. tenemos descripciones como "Centro Cultural Miguel Delibes", "Museo de la Ciencia"). ¿Es suficiente con eso?

**Comment by adrm** [comment]
Estoy de acuerdo en que puede que de momento sea suficiente, la verdad. Por mí, cerramos.

**Comment by nukeador** [comment]
Sí, lo he estado pensado varias veces, el nombre suele definir lo que es o qué hace.
