### ISSUE TITLE
[Nuevo sitio] laurldelsitio.com

### ISSUE THREAD

**Issue by ihsanshade** [PucelaBits/websegura#223]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Albacete/Castilla-La Mancha: MiProvincia/MiComunidad

```
{
    "url": "https://www.abengibre.es/",
    "name": "Abengibre",
    "tags": ["ayuntamientos"]
},
{
    "url": "https://abengibre.sedipualba.es/default.aspx",
    "name": "Sede electrónica de Abengibre",
"tags": ["ayuntamientos"]
},
{
    "url": "www.web3.com",
    "name": "El Nombre3",
    "twitter": "usuarioTwitter"
}
```

**Comment by ihsanshade** [comment]
Espero que esta vez esté mejor cumplimentada la plantilla. He usado dos de los tres espacios para añadir sitios web, y he borrado las líneas correspondientes a los usuarios de Twitter, ya que he buscado y no tienen.

**Comment by adrm** [comment]
Estupendo, he creado la página de Albacete con esos dos dominios. Gracias por comprobar si tenían Twitter. Por ir al detalle, no hay que poner el protocolo (la parte de `https://`) ni nada después del .es o .com, pero lo corrijo y listo.

Gracias!
