### ISSUE TITLE
ign.es

### ISSUE THREAD

**Issue by keniakronos** [PucelaBits/websegura#224]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Provincia/Comunidad: MiProvincia/MiComunidad

```
{
    "url": "www.web1.com",
    "name": "El Nombre 1",
    "twitter": "usuarioTwitter1",
    "tags": ["ayuntamientos", "museos"]
},
{
    "url": "www.web2.com",
    "name": "El Nombre2",
    "twitter": "usuarioTwitter",
    "tags": ["fundaciones"]
},
{
    "url": "www.web3.com",
    "name": "El Nombre3",
    "twitter": "usuarioTwitter"
}
```

**Comment by adrm** [comment]
Hola, sabes si tiene twitter esa entidad?

**Comment by Keisial** [comment]
Su página web lista que es https://twitter.com/IGNSpain

**Comment by palmerabollo** [comment]
Ya está incluido https://github.com/PucelaBits/websegura/blob/bf7c100bd670c9d0068ed4f71f7b712e1da99b54/_data/general.json#L183. Cierro.
