### ISSUE TITLE
Ocultar enlace a twitter si la puntuación es B o superior

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#23]
**¿Está relacionado con un problema? Por favor detallalo.**
Las webs con puntuación en verde (B o superior) no deberían tener un enlace para pedirles nada en twitter.

**Describe la solución que te gustaría ver**
Ocultar el enlace de twitter para las webs que ya tienen B o superior.

**Describe las alternativas posible**
Mover los que tienen B o superior a una tabla diferente que no tenga la columna de twitter, como "hall de la fama"

**Comment by palmerabollo** [comment]
El `if security.score < 50` de https://github.com/PucelaBits/websegura/blob/main/index.njk#L24 intentaba eso. Pero es mejor usar la letra A, B, C... para ser consistentes en los colores que pintamos (rojo=mal, verde=bien) y cuándo se les pueden exigir explicaciones. Me la asigno.

**Comment by nukeador** [comment]
Creo que podemos cerrar esto con el commit que he hecho para mostrarlo con <70
