### ISSUE TITLE
Añadir DMARC

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#231]
### Venimos de https://github.com/PucelaBits/websegura/discussions/170

No sabemos cuándo lo van a incorporar en el observatory o si va a salir por si API, pero podemos tirar las consultas nosotros mismos, esto me recomiendan:

> 
> use the endpoint  https://scanner.dmarc.globalcyberalliance.org/scan/mozilla.com and link to https://dmarcguide.globalcyberalliance.org/#/tool-select?d=mozilla.org which includes more analysis. We've also been using internet.nl some internally and they do email testing e.g. https://internet.nl/mail/mozilla.org/559723/
> It looks they don't have a public API, but you can "curl -v 'https://internet.nl/mail/' --data-raw 'url=mozilla.org'" or you could poll a domain like https://internet.nl/mail/mozilla.org/ then scrape the results

**Comment by nukeador** [comment]
Una idea de cómo mostrarlo en la tabla:

![imagen](https://user-images.githubusercontent.com/531906/126365789-3937ee19-eca2-4acb-b84f-191216a28891.png)

Tootip: "Es posible suplantar emails con este dominio"

**Comment by nukeador** [comment]
![phising](https://user-images.githubusercontent.com/531906/126366114-102cbb92-883c-42f0-8a17-431ce6434cfa.png)

**Comment by nukeador** [comment]
Página de detalle de cada dominio, idea

![imagen](https://user-images.githubusercontent.com/531906/126367110-a587ef7b-87bf-4e98-a982-0270c3d50fca.png)

Enlazaríamos tanto el texto como el icono al resultado del análisis de email.

**Comment by nukeador** [comment]
Resultados a enlazar por ejemplo

https://dmarcguide.globalcyberalliance.org/#/tool-select?d=policia.es&r=s&s=none&lang=es

**Comment by nukeador** [comment]
Deberían tener tanto SPF como DMARC como true para no ser marcados como email vulnerable.

**Comment by nukeador** [comment]
También podemos usar esto si no queremos depender de un servicio externo

https://github.com/domainaware/checkdmarc

**Comment by nukeador** [comment]
Tenemos una primera iteración lista en producción. Habría que añadirle un par de detalles para mostrar estadísticas de cuántos cumplen y cuántos no.

@palmerabollo ¿el update está programado de forma semanal? ¿Impide si da error sobrescriba los datos válidos?

**Comment by nukeador** [comment]
Acabamos de añadir a producción la landing del análisis de los correos con algunas estadísticas

https://websegura.pucelabits.org/analisis-email/

**Comment by nukeador** [comment]
Cierro y vamos generando issues nuevos para mejoras. Gracias.

**Comment by palmerabollo** [comment]
Esa es la idea. Si da error fallará ese paso del workflow de github actions y no pasará al siguiente que es el que commitea los cambios.
