### ISSUE TITLE
Si un dominio nuevo no está en el listado de DMARC, se rompe el build

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#234]
https://github.com/PucelaBits/websegura/runs/3136640462?check_suite_focus=true#step:6:21

**Comment by nukeador** [comment]
@palmerabollo esto queda arreglado con a813885f55f83628f4a09fc3f2e7327855f97699 ¿no?

**Comment by palmerabollo** [comment]
Sí. Cierro. Si veis algo raro, reabrid o avisad, plz.
