### ISSUE TITLE
Mensaje de Twitter

### ISSUE THREAD

**Issue by XtoreX** [PucelaBits/websegura#236]
Como hablamos por Telegram...

Me gusta mucho el tema que habéis añadido, acerca de la seguridad del mail ante phising, hay que acostumbrarse un poco al icono, ya que al ser de color oscuro o no existir descoloca un poco inicialmente.

Habría que modificar el mensaje de Twitter para que indique (si lo hay) el riesgo del mail, ahora mismo sólo indicah el tema de HTTPS.

Un saludo.

**Comment by nukeador** [comment]
Sí, está pendiente porque el texto actualmente ya está al límite de caracteres. Lo ponemos como pendiente, gracias por la sugerencia.

**Comment by XtoreX** [comment]
Me he tomado la livencia de rehacer el texto de Twitter, os lo dejo aquí para que lo valoréis, si tiene alguna errata es porque lo hice desde el teléfono, aún sobrarían caracteres;

Hola @PucelaBits, vuestro servidor necesita actualizar las conexiones seguras (HTTPS) y el servicio de correo (SMTP).
Vía https://websegura.pucelabits.org #websegura by @PucelaBits
¡Revisadlo por favor!

**Comment by nukeador** [comment]
Hemos añadido un texto diferente dependiendo de los problemas que tengan.
