### ISSUE TITLE
Rutas a las URLs

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#24]
https://github.com/PucelaBits/websegura/blob/5b7ccf9c76373a763d6ff7442933125251753ba6/index.njk#L21

Parece que esto está generando sin http(s) antes:

https://websegura.pucelabits.org/www.centroculturalmigueldelibes.com

¿Quizá deberíamos poner http por si no tiene https y da error?

**Comment by palmerabollo** [comment]
He puesto https por ahora, para que al menos enlace a algo en la mayoría de los casos actuales (si no todos).
La pena es que el API de mozilla obliga a hacer la petición sin protocolo (ej. www.jcyl.es). Entonces podemos hacer una de estas dos cosas:
1. Tener otra url en el JSON (ej. "link_url": "https://www.jcyl.es) con la URL clicable.
2. Dejar la url completa en el json con el "http[s]://xxx" y quitarle el protocolo en el crawl.sh, justo antes de pasárselo como parámetro al API de Mozilla.

Pienso que la buena es la 2, ya que evita tener casi duplicado el campo en el JSON. Hago unas búsquedas a ver cómo quitarlo, que tengo el `sed` oxidado :)

**Comment by nukeador** [comment]
Y hay que tener en cuenta que webs como auvasa no tiene https y da error ahora, pero puede que a futuro tenga (esperemos)
