### ISSUE TITLE
www.cacabelos.org

### ISSUE THREAD

**Issue by spect84** [PucelaBits/websegura#246]
Provincia: León

```
{
    "url": "www.cacabelos.org",
    "name": "Ayuntamiento de Cacabelos",
    "twitter": "aytocacabelos",
    "tags": ["ayuntamientos"]
},

**Comment by nukeador** [comment]
Hola,

¿De qué provincia es este sitio?

Gracias

**Comment by spect84** [comment]
Hola, es de León. Esta provincia no tenía archivo json y me he permitido la
libertad de crearlo.

Un saludo, felicidades por la iniciativa.

**Comment by palmerabollo** [comment]
Ya está incluido https://github.com/PucelaBits/websegura/blob/main/_data/provincias/leon.json#L6. Cierro.
