### ISSUE TITLE
https://www.benavente.es/ - zamora

### ISSUE THREAD

**Issue by jjppaa** [PucelaBits/websegura#252]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Provincia/Comunidad: Zamora/Castilla y León

```
{
    "url": "www.benavente.es",
    "name": "Ayntamiento de Zamora",
    "twitter": "usuarioTwitter1",
    "tags": ["ayuntamientos"]
}
```

**Comment by nukeador** [comment]
Supongo que no es el ayuntamiento de Zamora, si no el ayuntamiento de Benavente ¿no?

¿Tienen twitter?

**Comment by jjppaa** [comment]
Correcto Ayuntamiento de Benavente
twitter.com/aytobenavente

**Comment by nukeador** [comment]
Hola,

Me estoy dando cuenta que no tenemos ninguna web en la provicia de Zamora. ¿Podrías recopilar cuales son las más importantes y las añadimos todas juntas con la del ayto. de Benavente?

Gracias.

**Comment by palmerabollo** [comment]
He revisado y ya existe Zamora y está incluido el Ayuntamiento de Benavente https://github.com/PucelaBits/websegura/blob/main/_data/provincias/zamora.json#L53. Cierro.
