### ISSUE TITLE
auva2030.es

### ISSUE THREAD

**Issue by josemmba** [PucelaBits/websegura#254]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Opcionalmente puedes añadir etiquetas (tags) [de esta lista](https://github.com/PucelaBits/websegura/blob/main/_data/tags.json), para ayudar a categorizar los sitios.

---

Valladolid/Castilla y León: Valladolid/Castilla y León

```
{
    "url": "www.auva2030.es",
    "name": "Agenda Urbana Valladolid 2030",
    "twitter": "usuarioTwitter1",
    "tags": ["ayuntamientos"]
},

```

**Comment by nukeador** [comment]
Añadida, debería aparecer pendiente de análisis en un rato.

**Comment by nukeador** [comment]
https://websegura.pucelabits.org/w/www!auva2030!es/
