### ISSUE TITLE
Házselo saber

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#3]
Sería maravilloso si cada sitio tuviera un botón para mandar un tuit al usuario de twitter de la web en cuestión.

Ejemplo:

"Hola @casaindiavll

🔒 La seguridad de vuestra web y usuarios puede ser comprometida si no actualizáis vuestras conexiones seguras (HTTPS).
⚠️ ¡Por favor revisadlo cuanto antes!

https://websegura.pucelabits.org/ 

#websegura /vía @PucelaBits"

Una herramienta para generar el enlace https://www.sharelinkgenerator.com/

**Comment by adrm** [comment]
Acabo de subir commit implementando esto! He cogido el texto de ejemplo que ponías prácticamente literal, se puede editar fácilmente en `index.njk`.
