### ISSUE TITLE
Documentación técnica

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#30]
Estaría bien tener en la parte final del readme una sección que explique como ejecutar una copia local de la web y qué framework usamos, para los usuarios técnicos que quieran participar.

**Comment by nukeador** [comment]
Hice una primera aproximación en el README, pero los expertos en el framework sois vosotros ;-)

**Comment by nukeador** [comment]
@adrm @palmerabollo ¿Podéis mirar si está actualizado el readme con los cambios que hicimos a los scripts?

¡Gracias!

**Comment by adrm** [comment]
Le he dado una vuelta al readme, no es que haya cambiado mucho pero creo que con lo que está es suficiente, tampoco tenemos nada demasiado complejo. Si os parece cierro este issue porque creo que de momento está bien así. Si tenéis alguna sugerencia más para el readme, comentad y reabrimos!
