### ISSUE TITLE
Escalar el escaneo

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#34]
Actualmente tenemos 50 webs con solo dos provincias incompletas.

Si queremos cubrir toda España, mínimo estamos hablando de 1300 webs.

Ahora mismo el script de escaneado no está optimizado para esto, no guardamos caché local y ejecutamos en cada commit un scan completo. No es escalable.

**Comment by nukeador** [comment]
Ideas:

- Solo actualizar una vez al día (o más si hay muchas webs)
- Pedir resultados a la api en bloques más pequeños.
- Guardar un caché con resultados.
- No pedir resultados nuevos cuando no es necesario.
- Actualizar cuando se cambian las urls, solo las que se han añadido.

**Comment by nukeador** [comment]
Para evitar cosas como #50 donde la tarea diaria tira un scan y los análisis han caducado, deberíamos pensar en alternativas.

¿Puede ser que tengamos que ejecutar a las 00:00 la petición de rescan sin escribir nada, y luego a la 1:00 ya pedir resultados y reemplazar archivos?

¿Puede que tengamos que tirar siempre del scan del historico y leer la ultima nota? (Pero el historico no detalla los test pasados y fallados)

**Comment by palmerabollo** [comment]
Pedir solo el escaneo a una hora y pedir los resultados al cabo de unas horas es una mejora "barata" de implementar.

El escaneo, cuando haya cientos de sitios, tardará un buen rato y no sé si la API de Mozilla nos acabaría haciendo _throttling_. Se podría implementar un algoritmo más inteligente, aprovechando que los resultados del escaneo no van a cambiar muy a menudo. A ver qué os parece esto:

```
SI el sitio es nuevo: pedir el escaneo
ELSE (existe, es decir, hay un fichero en _data/results):
   SI los datos del sitio son antiguos (mayor que X días): pedir el escaneo
   ELSE: skip
```

Con eso tendríamos los datos para sitios nuevos y no machacaríamos tanto la API. La pega es que el usuario podría ver datos de hasta X días de antigüedad y no hay una "fecha de última actualización" global. Podemos empezar con 1 día de antiguedad e irlo subiendo cuando tengamos más sitios y empiece a ser un problema.

**Comment by nukeador** [comment]
Me parece bien la propuesta, pero aún así creo que llegaría un momento en el que coincidirán muchos sitios que necesitan actualizarse.

Creo que no deberíamos borrar el escaneo anterior hasta que no tengamos uno nuevo como "FINISHED". Ya que ahora lo que pasa es que se borra el anterior y acabamos con uno sin datos. El histórico también debería ser algo similar para no saturar las peticiones.

**Comment by palmerabollo** [comment]
> no deberíamos borrar el escaneo anterior hasta que no tengamos uno nuevo como "FINISHED"

:+1: cuando la API devuelva el resultado, miramos si es FINISHED y entonces escribimos el fichero. En otro caso mantenemos el antiguo.

**Comment by nukeador** [comment]
Con las peticiones a los historiales, creo que con tener una petición cada semana es suficiente, ya que siempre va a devolver algo, no caducan. Y no se si podríamos también evitar perder los que ya tenemos por si por lo que sea se pierden en la api.

**Comment by palmerabollo** [comment]
Voy a hacer alguna prueba. No prometo nada.

**Comment by adrm** [comment]
¿Quizás con las mejoras de @palmerabollo podemos dar esto por hecho? ¿Hay alguna mejora pendiente que se os ocurra?

**Comment by nukeador** [comment]
De momento puede valer, pero hay que observar qué pasa cuando muchos sitios les toca actualización a la vez, lo mismo estamos en el mismo problema.

@palmerabollo ?

**Comment by palmerabollo** [comment]
Subido 🎉

**Comment by nukeador** [comment]
@palmerabollo si vamos a limitar a 100, ¿quizá podríamos hacer el scan diario? Lo digo porque haciendo las cuentas, si tuviéramos 1000 webs tardarían en actualizarse un mes las notas, y también queremos tenerlas cada poco días actualizadas.
