### ISSUE TITLE
Ignorar directorios que se modifican en el server

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#35]
Sospecho que deberíamos meter en el .gitignore los archivos y directorios que se cambian en el server al hacer deploy.

Que tenga ahora en mente:

- Los resultados del scan
- El css generado desde el sass

**Comment by adrm** [comment]
Acabo de eliminar el css generado, pero los resultados del scan entiendo que sí deberían guardarse en el repo porque ahora los tenemos en cuenta para ver si hay que volver a pedirlos o no. Cierro este issue, si lo he entendido mal me decís.
