### ISSUE TITLE
Paleta de colores apta para daltónicos

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#36]
**Describe el problema**
Los colores verde/rojo actual son problemáticos para personas daltónicas (~5% de la población). Deberíamos tratar de combinar el color actual con algún tipo de indicador (ej. señal de warning, fondo rayado, etc) que permita diferenciarlos.

**Para reproducirlo**
Entrar en la [página de Madrid](https://websegura.pucelabits.org/p/madrid/#resultados) y ver la tabla de resultados.

**Capturas de pantalla**
![Screenshot 2021-01-27 at 22 22 38](https://user-images.githubusercontent.com/673420/106056007-736df100-60ee-11eb-8bae-11fb4cd31e09.png)

**Comment by nukeador** [comment]
¿Qué recomiendan los estándares de accesibilidad?

El tener letras diferentes en la nota supongo que no es suficiente.

**Comment by palmerabollo** [comment]
He preguntado y, con la indicación de la letra, parece que es suficiente para diferenciar la info. La cierro, si alguien tiene problemas o más conocimiento que yo, que reabra.
