### ISSUE TITLE
[Nuevos sitios] fnmt

### ISSUE THREAD

**Issue by dariomehr** [PucelaBits/websegura#37]
{
      "url": "www.fnmt.es",
      "name": "Fábrica Nacional de Moneda y Timbre",
      "twitter": "CERESfnmt"
    },
    {
      "url": "www.sede.fnmt.gob.es",
      "name": "Sede electrónica de la FNMT",
      "twitter": "CERESfnmt"
    },
    {
      "url": "cert.fnmt.es",
      "name": "Certificados de la FNMT",
      "twitter": "CERESfnmt"
    }

**Comment by adrm** [comment]
¿Puedes abrir este cambio directamente como PR? Si tienes problemas, di y nos encargamos nosotros!

**Comment by nukeador** [comment]
Estoy con ello

**Comment by nukeador** [comment]
Gracias @dariomehr
