### ISSUE TITLE
[Nuevo sitio] INE, IGN, juntaelectoralcentral

### ISSUE THREAD

**Issue by dariomehr** [PucelaBits/websegura#41]
{
        "url": "ine.es",
        "name": "Instituto Nacional de Estadística",
        "twitter": "es_ine"
},
{
        "url": "www.juntaelectoralcentral.es",
        "name": "Junta Electoral Central",
        "twitter": "Congreso_Es"
},
{
        "url": "www.ign.es",
        "name": "Instituto Geográfico Nacional",
        "twitter": "IGNSpain"
}

**Comment by nukeador** [comment]
#42
