### ISSUE TITLE
Ordenar las tablas de sitios por algún criterio

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#44]
**Describe la solución que te gustaría ver**
Sitios ordenados de mejor a peor (o de peor a mejor).
Creo que con el filtro "sort" de eleventy https://www.11ty.dev/docs/collections/#sorting se podría hacer fácil.
Relacionada con #6 

**Describe las alternativas posible**
Otra alternativa puede ser implementar filtros más completos y que los títulos de las tablas sean clicables (estilo wikipedia, para ordenar), pero requiere algo más de conocimientos de frontend.

**Comment by nukeador** [comment]
Creo que alguna de las librerías que usamos de js ya tiene incluido el ordenamiento de tablas (creo),

**Comment by adrm** [comment]
He estado probando con usuarios y se espera que la tabla esté ordenada por nota, creo que sería lo mejor. No creo que ayude dar más posibilidades de ordenar la tabla, con que esté ordenada por nota sería suficiente y lo menos confuso.

**Comment by nukeador** [comment]
De momento ordené por URL en https://github.com/PucelaBits/websegura/blob/ad46da0a5c03efcdebbef7bb29c3638c03747774/_includes/tabla.njk#L11

El problema es que el objeto que tenemos no tiene las notas, solo los nombres, urls y twitters.

**Comment by palmerabollo** [comment]
Sí, creo que haría falta hacer un filtro custom, similar al `| color` que tenemos, que haga la ordenación consultando el fichero con las notas (no estoy seguro de que se pueda, sé poco aún de 11ty/njk)

**Comment by adrm** [comment]
Ya están todas las tablas ordenadas de menos a más seguro.
