### ISSUE TITLE
Añadir soporte para comunidades uniprovinciales

### ISSUE THREAD

**Issue by fjaguero** [PucelaBits/websegura#48]
**¿Está relacionado con un problema? Por favor detallalo.**
Ahora mismo es necesario contar con el listado de webs de una comunidad para luego poder linkear las webs de las provincias y que estas se muestren en la navegación principal. 

En el caso de las comunidades uniprovinciales (Murcia, La Rioja, Cantabria, Asturias, la Comunidad de Madrid, Navarra y Baleares), es necesario crearo un .json vacío para así incluir las webs en el fichero de provincia y que así se puedan ser navegables.

**Describe la solución que te gustaría ver**
Posibilidad de crear un .json de provincia que sea navegable, sin necesidad de incluir un archivo vacío de comunidad.

**Describe las alternativas posible**
Listar las comunidades que no tengan provincias en la navegación

**Comment by fjaguero** [comment]
Esto lo hemos visto al añadir La Rioja. Ahora mismo hemos metido el "hack" de incluir el listado de webs de la comunidad como un array vacío.

**Comment by adrm** [comment]
En el caso de Madrid, por ejemplo, creo que tiene sentido la división entre comunidad y provincia porque eso nos ayudó a dividir las webs que dependían de la comunidad de las que dependen de niveles inferiores. Creo que este mismo planteamiento tendría sentido para el resto de comunidades uniprovinciales.

**Comment by nukeador** [comment]
Lo de Madrid puede ser más fácil porque el volumen de webs es enorme, pero en el resto de uniprovinciales, sospecho que no habrá tantas y muchas son de uso tanto la capital como en el resto.

@fjaguero ¿en el caso de La Rioja es algo así?

**Comment by fjaguero** [comment]
@nukeador No, en el caso de La Rioja ya de por si hay pocos organismos. Los que ya están serán el 80% si nos centramos en los más relevantes (viendo el listado oficial de la web de la comunidad).

**Comment by nukeador** [comment]
De momento en f6793b1c001a3ef9f6a87464a0df60913329cfa7 he ocultado que se muestra nada de la comunidad si el array de webs está vacío. Esto de momento permite que añadamos una provincia y una comunidad vacía para las uniprovinciales.

**Comment by nukeador** [comment]
Hay un fix adicional, que es que si el archivo de provincia no define comunidad alguna, esta se oculta. Creo que de momento con esto nos vale para crear uniprovinciales.
