### ISSUE TITLE
La tarea diaria rompe los datos de análisis

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#50]
La tarea diaria no es la primera vez que devuelve que no hay análisis recientes, borrando todos los datos de análisis

https://github.com/PucelaBits/websegura/commit/7fdc26dfdf4b4bd346dd3c2ce88bf48a3f313251

**Comment by nukeador** [comment]
¿Lo mismo deberíamos pedir un scan diario, pero luego recuperar los datos del último histórico?

https://http-observatory.security.mozilla.org/api/v1/getHostHistory?host=www.uva.es

**Comment by nukeador** [comment]
Sospecho que como el scan caduca en 24h, cuando lo pedimos con el cron no le da tiempo a hacer el rescan y nos dice que no hay scans recientes

![imagen](https://user-images.githubusercontent.com/531906/106599354-3aec6e00-6559-11eb-907a-fb2d67ac6bf9.png)

**Comment by palmerabollo** [comment]
He subido un commit y los datos ya no se borrarán. Además, se machaca un fichero existente solo si mozilla devuelve éxito (FINISHED), para evitar sobrescribir un fichero exitoso antiguo con uno erroneo nuevo.
