### ISSUE TITLE
Cambiar notas estilo americano por algo más comprensible en España

### ISSUE THREAD

**Issue by adrm** [PucelaBits/websegura#51]
**¿Está relacionado con un problema? Por favor detallalo.**
Las notas estilo americano con letras no son comprensibles en general por el público español.

**Describe la solución que te gustaría ver**
Mostrar las notas de 0 a 10 como acostumbramos por aquí, quizás en formato "X/10" directamente para que se entienda que es una nota sobre 10.

El emoji de la calavera es extremadamente claro, quizás podemos hacer una escala menos precisa de 4 o 5 emojis que cada uno abarque 2 o 3 notas.

**Comment by nukeador** [comment]
El problema que tengo con las notas numéricas es que la gente puede pensar que un 5 un 6 está genial. Cuando la verdad es que no aprobarían si no tienen 70/100 (es el mínimo de seguridad que pedimos)

**Comment by palmerabollo** [comment]
Pienso que con los etiquetados energéticos de electrodomésticos, vivienda, bombillas... los rankins A..F no estan mal. Estoy de acuerdo con lo que dice nuke, habría que hacer algún mapeo A=10, B=6 C=4, D=2, E=1, F=0, o algo no lineal para que no de la impresión de que una D+ es un aprobado con un 5

**Comment by nukeador** [comment]
@adrm ¿lo dejamos de momento como está a menos que recibamos feedback de la gente de que no se entiende?

**Comment by adrm** [comment]
Sí, entiendo que no es muy prioritario. Con los colores también se entiende bastante bien y quien no entienda las letras pues pasará de ello y listo.
