### ISSUE TITLE
Añadir la provincia de Málaga

### ISSUE THREAD

**Issue by fcoterroba** [PucelaBits/websegura#54]
Provincia (o comunidad autónoma si es web regional): Málaga

{
        "url": "www.malaga.eu",
        "name": "Málaga",
        "twitter": "malaga"
}

**Comment by nukeador** [comment]
Hola,

¡Gracias por el aporte!

¿Alguna otra web de la provincia de Málaga que te gustaría añadir?  Así aprovechamos y las metemos todas a la vez en el nuevo archivo que hay que crear (no te preocupes, nos encargamos de esto)

Un saludo.

**Comment by fcoterroba** [comment]
Gracias Nukeador! Lamento no haberlo hecho correctamente. Estaré atento para ver cómo hacerlo correctamente la próxima vez.
Como dices, aprovecho para ponerte un listado de algunos pueblos de la provincia de Málaga:

- [Ayuntamiento de Marbella](www.marbella.es) 6/11--> F
- [Ayuntamiento de Alhaurín de la Torre](https://alhaurindelatorre.es/)  7/11 --> D
- [Ayuntamiento de Cártama](http://www.cartama.es/) 5/11 --> F
- [Ayuntamiento de Alhaurín el Grande](https://alhaurinelgrande.es/) 5/11 --> F
- [Ayuntamiento de Istán](http://www.istan.es/es/) 5/11 --> F

**Comment by nukeador** [comment]
¡Gracias! ¿Tenemos los twitter de estas webs para añadirlos también?

Este caso es especial porque aún no tenemos la provincia, por eso crearlo desde la interfaz de github es un poco complejo.

Una vez tengamos los twitter te los puedo meter en un archivo en _data/provincias con el mismo formato:

```
{
    "url": "www.web.com",
    "name": "El Nombre",
    "twitter": "usuarioTwitter"
},
{
    "url": "www.web.com",
    "name": "El Nombre",
    "twitter": "usuarioTwitter"
}
```

**Comment by fcoterroba** [comment]
Por supuesto Nuke!

Quedaría algo más o menos así:

---
```json
{
    "url": "https://www.marbella.es/",
    "name": "Ayuntamiento de Marbella",
    "twitter": "Ayto_Marbella"
},
{
    "url": "http://www.cartama.es/",
    "name": "Ayuntamiento de Cártama",
    "twitter": "Ayto_Cartama"
},
{
    "url": "https://alhaurinelgrande.es/",
    "name": "Ayuntamiento de Alhaurín el Grande",
    "twitter": "Ayto_Alhaurin"
},
{
    "url": "http://www.istan.es/es/",
    "name": "Ayuntamiento de Istán",
    "twitter": "AytoIstan"
}
```
Alhaurín de la Torre no tiene Twitter por lo que veo así que no lo añado

**Comment by nukeador** [comment]
Muchas gracias, debería aparecer en unos minutos en la web.

**Comment by nukeador** [comment]
https://websegura.pucelabits.org/p/malaga/
