### ISSUE TITLE
[Nuevo sitio] Comunidad Foral de Navarra - comunidad

### ISSUE THREAD

**Issue by mainmind83** [PucelaBits/websegura#57]
{
  "name": "Comunidad Foral de Navarra",
  "webs": [
    {
      "url": "www.navarra.es",
      "name": "Navarra",
      "twitter": "gob_na"
    },
    {
      "url": "bon.navarra.es",
      "name": "Boletín Oficial de Navarra",
      "twitter": "navarra"
    },
    {
      "url": "hacienda.navarra.es",
      "name": "Hacienda Navarra",
      "twitter": "navarra"
    },
    {
      "url": "www.sodena.com",
      "name": "Start Up Capital Navarra - SODENA",
      "twitter": "sodenavarra"
    }
  ]
}

**Comment by nukeador** [comment]
Muchas gracias por la aportación.

Ya está disponible en

https://websegura.pucelabits.org/c/navarra/
