### ISSUE TITLE
[Nuevo sitio] Comunidad Foral de Navarra - provincias

### ISSUE THREAD

**Issue by mainmind83** [PucelaBits/websegura#58]
{
  "name": "Comunidad Foral de Navarra",
  "comunidad": "navarra",
  "webs": [
    {
      "url": "www.pamplona.es",
      "name": "Ayuntamiento de Pamplona",
      "twitter": "Pamplona_ayto"
    },
    {
      "url": "www.olite.es",
      "name": "Ayuntamiento de Olite",
      "twitter": ""
    },
    {
      "url": "www.cendeadegalar.es",
      "name": "Ayuntamiento de la Cendea de Galar",
      "twitter": ""
    },
    {
      "url": "www.mcp.es",
      "name": "Mancomunidad comarca de Pamplona",
      "twitter": "mcp_info"
    },
    {
      "url": "www.mairaga.es",
      "name": "Mancomunidad de Mairaga",
      "twitter": "emvsmadrid"
    },
    {
      "url": "www.animsa.es",
      "name": "Asociación Navarra de informática Municipal",
      "twitter": "animsa"
    },
    {
      "url": "www.cener.es",
      "name": "Centro nacional de energías renovables",
      "twitter": "CENER_energia"
    },
    {
      "url": "www.cein.es",
      "name": "Centro Europeo de Empresas e Innovación de Navarra",
      "twitter": "ceinnavarra"
    },
    {
      "url": "www.pamplonetario.org",
      "name": "Planetario de Pamplona",
      "twitter": "pamplonetario"
    }

  ]
}

**Comment by nukeador** [comment]
Muchas gracias por la aportación.

Ya está disponible en

https://websegura.pucelabits.org/p/navarra/

**Comment by nukeador** [comment]
@mainmind83 El dominio cener.es parece que no existe, ¿puedes comprobarlo?

**Comment by mainmind83** [comment]
Mea culpa: www.cener.com
