### ISSUE TITLE
Ranking de mejores y peores organismos

### ISSUE THREAD

**Issue by palmerabollo** [PucelaBits/websegura#6]
Permitir ordenar la tabla, o mostrar de algún modo quiénes son los mejores sitios públicos.
Le daría también un enfoque "en positivo" al sitio.

**Comment by nukeador** [comment]
Sí, separar los que tienen B o superior de resto en verde es importante como "Hall de la fama"

Deberíamos usar la misma paleta de colores para cada letra que usa el observatory

**Comment by nukeador** [comment]
Y quizá sería bueno si se puede, ordenar la lista por nota de menos a más por defecto.

**Comment by nukeador** [comment]
Y sería bueno saber qué score es el que dice claramente que no hay ni https, posiblemente 10 o menos.

**Comment by nukeador** [comment]
Idea, se podría crear una página independiente "Hall de la fama" con todas las webs que tienen A o B y de qué provincia o comunidad son, así como otra página "Hall de la vergüenza" para todas las webs que pasaron menos de 5 tests (que es lo que usamos ahora para identificar la mayoría que no tienen ni HTTPS)
