### ISSUE TITLE
websegura.pucelabits.org/p/valencia/

### ISSUE THREAD

**Issue by cuantocarlos** [PucelaBits/websegura#63]
,
      {
        "url": "sede.valencia.es",
        "name": "Sede electónica València",
        "twitter": "AjuntamentVLC"
      },
      {
        "url": "www.albaida.es",
        "name": "Ajuntament d'Albaida",
        "twitter": "AjAlbaida"
      },
      {
        "url": "www.alcasser.es",
        "name": "Ayuntamiento de Alcasser",
        "twitter": "AjuntAlcasser"
      },
      {
        "url": "www.alfaradelabaronia.es",
        "name": "Ayuntamiento de Alfara",
        "twitter": "aytoalfara"
      },
      {
        "url": "www.alfarrasi.es",
        "name": "Ajuntament Alfarrasí",
        "twitter": "Ajunt_Alfarrasi"
      },
      {
        "url": "www.algardepalancia.es",
        "name": "Ajuntament d'Algar",
        "twitter": "AjAlgar"
      },
      {
        "url": "www.algemesi.es",
        "name": "Ajuntament Algemesí",
        "twitter": "algemesi_net"
      },
      {
        "url": "www.algimiadealfara.es",
        "name": "Ajuntament d'Algímia",
        "twitter": "AAlgimia"
      },
      {
        "url": "www.alginet.es",
        "name": "Ajuntament d'Alginet",
        "twitter": "aj_alginet"
      },
      {
        "url": "www.alpuente.es",
        "name": "Ayuntamiento de Alpuente",
        "twitter": "AlpuenteA"
      },
      {
        "url": "www.andilla.es",
        "name": "Ayuntamiento Andilla",
        "twitter": "andillaayto"
      },
      {
        "url": "www.antella.es",
        "name": "Ajuntament d'Antella",
        "twitter": "AjAntella"
      },
      {
        "url": "www.barxeta.es",
        "name": "Ayuntamiento de Barxeta",
        "twitter": "Ajunt_Barxeta"
      },
      {
        "url": "benetusser.es",
        "name": "Ayuntamiento de Benetússer",
        "twitter": "AyuntBenetusser"
      },
      {
        "url": "beniculldexuquer.es",
        "name": "Ajuntament de Benicull de Xúquer",
        "twitter": "BenicullXu"
      },
      {
        "url": "www.beniganim.es",
        "name": "Ajuntament de Benigànim",
        "twitter": "ajbeniganim"
      },
      {
        "url": "benirredra.es",
        "name": "Ajuntament de Benirredrà",
        "twitter": "Benirredra"
      },
      {
        "url": "betera.es",
        "name": "Ajuntament de Bétera",
        "twitter": "Aytobetera"
      },
      {
        "url": "bicorp.es",
        "name": "Ayuntamiento de Bicorp",
        "twitter": "AyuntBicorp"
      },
      {
        "url": "bocairent.es",
        "name": "Ayuntamiento de Bocairent",
        "twitter": "Aj_Bocairent"
      },
      {
        "url": "bonreposimirambell.es",
        "name": "Ayuntamiento de Bonrepòs y Mirambell",
        "twitter": "BiMajuntament"
      },
      {
        "url": "www.carcaixent.es",
        "name": "Ayuntamiento de Carcaixent",
        "twitter": "AjCarcaixent"
      },
      {
        "url": "camporrobles.es",
        "name": "Ayuntamiento de Camporrobles",
        "twitter": "ACamporrobles"
      },
      {
        "url": "castielfabib.es",
        "name": "Ayuntamiento de Castielfabib ",
        "twitter": "AyuCastielfabib"
      },
      {
        "url": "catadau.es",
        "name": "Ajuntament de Catadau",
        "twitter": "AjCatadau"
      },
      {
        "url": "catarroja.es",
        "name": "Ayuntamiento de Catarroja",
        "twitter": "ajuntcatarroja"
      },
      {
        "url": "www.chera.es",
        "name": "Ayuntamiento de Chera",
        "twitter": "Chera"
      },
      {
        "url": "chiva.es",
        "name": "Ayuntamiento de Chiva",
        "twitter": "AyuntaChiva"
      },
      {
        "url": "chulilla.es",
        "name": "Ayuntamiento de Chulilla",
        "twitter": "aytochulilla"
      },
      {
        "url": "corbera.es",
        "name": "Ajuntament de Corbera",
        "twitter": "AjuntCorbera"
      },
      {
        "url": "cullera.es",
        "name": "Ajuntament de Cullera",
        "twitter": "MIA_Cullera"
      },
      {
        "url": "visit-cullera.es",
        "name": "Cullera Turismo",
        "twitter": "visitcullera"
      },
      {
        "url": "elpalomar.es",
        "name": "Ayuntamiento de El Palomar",
        "twitter": "ajelpalomar"
      },
      {
        "url": "elperello.es",
        "name": "Ajuntament de El Perelló",
        "twitter": "ElPerello_ayto"
      },
      {
        "url": "www.elpuig.es",
        "name": "Ajuntament del Puig",
        "twitter": "ajunt_elpuig"
      },
      {
        "url": "elpuigturistico.net",
        "name": "Turismo El Puig",
        "twitter": "elpuigturistico"
      },
  ]
}

**Comment by nukeador** [comment]
Hola @cuantocarlos ¿son todas webs nuevas? Veo algunas que ya tenemos en https://github.com/PucelaBits/websegura/blob/main/_data/provincias/valencia.json

¿Puedes listar sólo las que quieres cambiar? O también puedes dar editar al archivo aquí directamente y decirle que lo envíe como propuesta (lo que generará un PR)

**Comment by nukeador** [comment]
@cuantocarlos creo que el PR de @jtorrex metió todo esto, si no avisa y volvemos a abrir.

**Comment by cuantocarlos** [comment]
Edité el archivo

**Comment by nukeador** [comment]
> archivo

Hola Carlos, ¿dónde editaste el archivo? No veo ningún PR con los cambios. ¿Quizá lo editaste sólo en tu fork? Si tienes dudas escríbenos por el chat y vemos.

Un saludo.
