### ISSUE TITLE
Mejorar la propia puntuación de la web en el observatory

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#7]
Para predicar con el ejemplo, deberíamos actualizar las cabeceras de la propia web para que puntuara mejor en el observatory, ahora mismo da un D+

https://observatory.mozilla.org/analyze/websegura.pucelabits.org

Entiendo que algunas cosas se podrán hacer y otras no, ya que dependen de la configuración de HTTPS del servidor de github pages.

**Comment by nukeador** [comment]
@palmerabollo @adrm ¿Sabemos si esto es posible con meta tags? ¿O quizá solo parte?

![imagen](https://user-images.githubusercontent.com/531906/105052401-221b8d00-5a70-11eb-8bcf-af5a0c179ff4.png)

**Comment by adrm** [comment]
He estado mirando y creo que GitHub no permite modificar headers. La solución más fácil que se me ocurre sería cambiar el despliegue a Netlify, que el plan gratuito es suficientemente generoso y permite cambiar headers a placer.

**Comment by palmerabollo** [comment]
El único que se puede cambiar, porque [se puede cambiar con un <meta http-equiv="Content-Security-Policy" content="loquesea">](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#examples) es el primero, con el que subiríamos 25 puntos. Los otros no se puede, hasta donde yo sé.

Sobre Netlify, como veais, yo no lo usado nunca. Sí que parece que hay github actions para desplegar ahí https://github.com/marketplace/actions/netlify-actions.

**Comment by nukeador** [comment]
¿En qué puntuación nos quedamos con el meta que podemos meter?

**Comment by nukeador** [comment]
Vale, con solo eso tenemos ya una B, peeeero, hay quitar los style-inline que tenemos ahora mismo para las filas coloreadas que metemos inline.

@adrm @palmerabollo Supongo que habría que crear tres clases y aplicarlas desde el css sin meterlo inline ¿no?

**Comment by nukeador** [comment]
https://github.com/PucelaBits/websegura/issues/27

**Comment by nukeador** [comment]
![imagen](https://user-images.githubusercontent.com/531906/105209414-17cdc180-5b4a-11eb-8a51-205e59c88f42.png)
