### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#71]
Error en el build

https://github.com/PucelaBits/websegura/runs/1848936789#step:6:183

**Comment by adrm** [comment]
Vale, ya he visto el problema, no encajaba bien el cambio que hice con la mejora que hizo Guido. Ahora subo un cambio para que se queden los resultados a undefined si no están disponibles y que no pete la build. En esos casos la página aparecerá como pendiente mientras no esté disponible el resultado, que entiendo que es lo mismo que pasa ahora.
