### ISSUE TITLE
[Nuevo sitio] https://www.soria.es/

### ISSUE THREAD

**Issue by jda-tid** [PucelaBits/websegura#76]
Provincia: Soria

```
{
    "url": "https://www.soria.es/",
    "name": "Ayuntamiento de Soria",
    "twitter": "Ayto_Soria"
}
```

**Comment by nukeador** [comment]
Hola, gracias por la aportación, en unos minutos debería aparecer en la web.

Si tienes más webs, no dudes en mandárnoslas por aquí o editar el archivo:

https://github.com/PucelaBits/websegura/blob/main/_data/provincias/soria.json
