### ISSUE TITLE
Menciones en medios

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#78]
Estaría bien tener una zona/sección/lugar en la web para enlazar las menciones en los medios.

@dafnecalvo ¿alguna idea de la mejor forma de mostrar esto? :-)

**Comment by DafneCalvo** [comment]
¡Sí! Habitualmente las apariciones en prensa no incluyen mucha información, en ocasiones solo el enlace y el medio de comunicación. En mi opinión, sería genial si se incluyera a. Medio, b. Titular, c. Nombre del medio, d. Fecha de apartición, e. Un pequeño fragmento sobre la noticia, f. Un enlace. Algo como: https://ifuturo.org/apariciones-en-medios/

Las piezas se ordenarían cronológicamente, por orden de aparición.

**Comment by nukeador** [comment]
Genial, gracias por la guía :+1:

**Comment by nukeador** [comment]
He hecho una primera implementación para que sólo se tenga que editar el archivo markdown, así @DafneCalvo si quieres le echas mano.

https://github.com/PucelaBits/websegura/blob/main/pages/medios.md

La página está en:

https://websegura.pucelabits.org/medios/

Y enlazada al pie de todas las páginas en la sección "Más información"
