### ISSUE TITLE
Undefined tests_quantity

### ISSUE THREAD

**Issue by nukeador** [PucelaBits/websegura#79]
Parece que no estamos recogiendo bien tests_quantity en las tablas. Curiosamente en el detalle de cada web sí que no toma bien.

https://github.com/PucelaBits/websegura/blob/4b947f9bbc5c044b8a69eb6a1707af8b840ac5ff/.eleventy.js#L109

**Comment by nukeador** [comment]
@adrm te asigné esta pero no se si es algo que estabas mirando ahora o quieres que mire otra persona.

**Comment by adrm** [comment]
Sí, entiendo que es por algún cambio que hice yo y tengo pendiente mirarlo, pero no me he puesto aún.

**Comment by adrm** [comment]
Resuelto, era una tontería, siento no haberle echado un vistazo antes porque ha sido un segundo.
