### ISSUE TITLE
Web Jerez de la Frontera

### ISSUE THREAD

**Issue by ancafe** [PucelaBits/websegura#87]
{
    "url": "https://www.sedeelectronica.jerez.es/",
    "name": "Jerez de la Frontera - Sede Electrónica",
    "twitter": "ciudadjerez"
},
{
    "url": "https://www.jerez.es",
    "name": "Ayuntamiento de Jerez de la Frontera",
    "twitter": "ciudadjerez"
}

**Comment by nukeador** [comment]
Muchas gracias por el aporte. En unos minutos debería aparecer en la web.
