### ISSUE TITLE
[Nuevo sitio] https://www.juntadeandalucia.es/organismos/empleoformacionytrabajoautonomo/sae.html

### ISSUE THREAD

**Issue by PRQuevedo** [PucelaBits/websegura#88]
Por favor usa la siguiente plantilla para especificar la url, nombre y cuenta en twitter (si existe, o del organismo que dependa), puedes añadir múltiples sitios.

Provincia/Comunidad: Sevilla/Andalucía

```
{
    "url": "https://www.juntadeandalucia.es/organismos/empleoformacionytrabajoautonomo/sae.html",
    "name": "Servicio Andaluz de Empleo. Junta de Andalucía",
    "twitter": "SAEmpleo"
},
{
    "url": "https://ws054.juntadeandalucia.es/eureka2/eureka-demandantes/busquedaOfertas.do",
    "name": "Portal de ofertas de trabajo del Servicio Andaluz de Empleo. Junta de Andalucía",
    "twitter": "SAEmpleo"
}
```

**Comment by nukeador** [comment]
Hola,

Gracias por el aporte. Las dos URLs que indicas ya forman parte del análisis que hacemos del dominio juntadeandalucia.es en

https://github.com/PucelaBits/websegura/blob/df52272bbc6804cadd57cb29ec79f3442e2254cd/_data/comunidades/andalucia.json#L5

Por lo que la nota de seguridad debería ser la misma que sale en:

https://websegura.pucelabits.org/c/andalucia/

Si tienes algún dominio nuevo, no dudes en enviárnoslo y lo añadiremos a la web. 

Un saludo y ¡muchas gracias de nuevo!
