### ISSUE TITLE
[Nuevo sitio] Defensor del Pueblo de Navarra

### ISSUE THREAD

**Issue by urko1982** [PucelaBits/websegura#92]
{
    "url": "www.defensornavarra.com",
    "name": "Defensor del Pueblo de Navarra",
    "twitter": "@gob_na"
},

**Comment by nukeador** [comment]
Hola,

Dado que no tenemos aún ninguna web de Navarra, ¿hay alguna otra web que te gustaría añadir para así meterlas todas juntas?

Si no hay twitter de alguna web podemos poner el del organismo del que dependan.

Gracias.

**Comment by urko1982** [comment]
Hola

La mayoría son subdominios de navarra.es como bon.navarra.es (Boletín Oficial de Navarra),  www.turismo.navarra.es (Turismo de Navarra) o sitna.navarra.es (Sistema de información territorial de Navarra)

{
"url": "www.navarra.es",
"name": "Información, servicios y trámites del Gobierno de Navarra",
"twitter": "@gob_na"
},

{
"url": "www.parlamentodenavarra.es",
"name": "Página del Parlamento de Navarra",
"twitter": "@parlamentoNA"
},

Luego están lógicamente las de los ayuntamientos (a destacar la de la capital)

{
"url": "www.pamplona.es",
"name": "Página de Ayuntamiento de Pamplona",
"twitter": "@010_Pamplona"
},

**Comment by nukeador** [comment]
Muchas gracias, en unos minutos deberían aparecer en la web.
