### ISSUE TITLE
[Nuevo sitio] Diputaciones y capitales País Vasco

### ISSUE THREAD

**Issue by Davidbf** [PucelaBits/websegura#99]
País Vasco
{
    "url": "www.irekia.euskadi.eus",
    "name": "Transparencia y participación ciudadana en Eusko Jaurlaritza - Gobierno Vasco.",
    "twitter": "Irekia"
}

Álava/País Vasco
{
    "url": "web.araba.eus",
    "name": "Web institucional de la Diputación Foral de Álava",
    "twitter": "Araba"
},
{
    "url": "www.vitoria-gasteiz.org",
    "name": "Sitio Web Oficial del Ayuntamiento de Vitoria-Gasteiz",
    "twitter": "vitoriagasteiz"
}

Guipúzcoa/País Vasco
{
    "url": "www.gipuzkoa.eus",
    "name": "Portal de la Diputación Foral de Gipuzkoa",
    "twitter": "Gipuzkoa"
},
{
    "url": "www.donostia.eus",
    "name": "Web Oficial del Ayuntamiento de Donostia – San Sebastián",
    "twitter": "Ayto_SS"
}

Vizcaya/País Vasco
{
    "url": "web.bizkaia.eus",
    "name": "Web institucional de la Diputación Foral de Bizkaia",
    "twitter": "Bizkaia"
},
{
    "url": "www.bilbao.eus",
    "name": "Sitio Web del Ayuntamiento de Bilbao",
    "twitter": "bilbao_udala"
}

**Comment by nukeador** [comment]
Muchas gracias, ya están añadidas, tardarán unos minutos en salir en la web.
